networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: shaiksuhail2767/mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  catalogue:
    image: shaiksuhail2767/catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop 
  user:
    image: shaiksuhail2767/user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
  cart:
    image: shaiksuhail2767/cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis
  mysql:
    image: shaiksuhail2767/mysql:v1
    container_name: mysql
    networks:
      - roboshop
  shipping:
    image: shaiksuhail2767/shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
  payment:
    image: shaiksuhail2767/payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq
  web:
    image: shaiksuhail2767/web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment